# For more info on HTTP files go to https://aka.ms/vs/httpfile
@host = https://localhost:7076/api
@categoryId = 8e3551c9-eee2-41a3-6a1d-08dc06dedac7

GET {{host}}/Categories

###
POST {{host}}/categories
Content-Type: application/json

{
  "name": "Math",
  "description" : "this for all exam of type Math"
}

###
DELETE {{host}}/categories/{{categoryId}}

###
PUT {{host}}/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Math",
  "description" : "this for all exam of type Math upd"
}
###
GET {{host}}/categories/{{categoryId}}/exams
###
POST {{host}}/categories/{{categoryId}}/exams
Content-Type: application/json

{
  "title": "Final Java Exam",
  "duration": "02:30:00",
  "date": "2020-09-10",
  "totalMarks": "500.300",
  "term": 1,
  "level": 3
}
###
@examId = 34fca573-2191-403d-eaa0-08dc06de8101
PUT {{host}}/categories/{{categoryId}}/exams/{{examId}}
Content-Type: application/json

{
  "title": "Final Java Exam",
  "duration": "02:30:00",
  "date": "2020-09-10",
  "totalMarks": "150",
  "term": 1,
  "level": 3
}
###
DELETE {{host}}/categories/{{categoryId}}/exams/2022b5ef-6f77-4def-1c49-08dc06df8e2e
###
GET {{host}}/multiplechoicequestions/
###
POST {{host}}/multiplechoicequestions/
Content-Type: application/json

{
  "title": "what is the first letter in mohamed?",
  "difficulty": 2,
  "mark": 10,
  "optionA": "m",
  "optionB": "M",
  "optionC": "Cs",
  "optionD": "sh",
  "correctChoice": "A"
}
###
@MquestionId = 254bdfe8-49fc-489f-4558-08dc07a1c3e4
PUT {{host}}/multiplechoicequestions/{{MquestionId}}
Content-Type: application/json

{
  "title": "what is the first letter in mohamed?",
  "difficulty": 2,
  "mark": 10,
  "optionA": "m",
  "optionB": "M",
  "optionC": "Cs",
  "optionD": "sh",
  "correctChoice": "A"
}